import React, { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import {
  ArrowLeft, Plus, Trash2, Calculator, FileText, CheckCircle2,
  Sparkles, Loader2, Globe, AlertCircle, Download, Zap
} from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuth } from '@/contexts/AuthContext';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

// ── i18n ──────────────────────────────────────────────────────────────────────
const T = {
  en: {
    code: 'EN', label: 'English',
    title: 'AI GST Assistant',
    subtitle: 'Auto-calculate GST liability, draft GSTR-1, and get AI compliance checklist for your month.',
    yourBiz: 'Your Business',
    bizType: 'Business Type',
    bizState: 'Your State (place of business)',
    salesEntries: 'Monthly Sales Entries',
    addEntry: 'Add Entry',
    buyerName: 'Buyer Name',
    buyerState: 'Buyer State',
    taxableAmt: 'Taxable Amount (₹)',
    gstRate: 'GST Rate',
    hsn: 'HSN/SAC',
    invoiceNo: 'Invoice #',
    calculate: 'Calculate GST & Generate GSTR-1',
    calculating: 'AI is analysing your data…',
    results: 'Results',
    gstLiability: 'GST Liability Breakdown',
    cgst: 'CGST', sgst: 'SGST', igst: 'IGST', total: 'Total GST Payable',
    totalSales: 'Total Taxable Sales',
    gstr1: 'Draft GSTR-1 Summary',
    checklist: 'Compliance Checklist',
    aiInsights: 'AI Insights',
    noEntries: 'Add at least one sales entry to calculate GST.',
    intra: 'Intra-state', inter: 'Inter-state',
    download: 'Download as CSV',
    notice: 'Math is deterministic. Compliance checklist is generated by Gemini AI for guidance only — verify with your CA before filing.',
  },
  hi: {
    code: 'HI', label: 'हिन्दी',
    title: 'AI GST सहायक',
    subtitle: 'GST देयता की स्वतः गणना करें, GSTR-1 का ड्राफ्ट तैयार करें, और इस महीने की AI अनुपालन चेकलिस्ट प्राप्त करें।',
    yourBiz: 'आपका व्यवसाय',
    bizType: 'व्यवसाय प्रकार',
    bizState: 'आपका राज्य (व्यवसाय स्थान)',
    salesEntries: 'मासिक बिक्री प्रविष्टियाँ',
    addEntry: 'प्रविष्टि जोड़ें',
    buyerName: 'खरीदार का नाम',
    buyerState: 'खरीदार का राज्य',
    taxableAmt: 'कर योग्य राशि (₹)',
    gstRate: 'GST दर',
    hsn: 'HSN/SAC',
    invoiceNo: 'चालान #',
    calculate: 'GST गणना करें और GSTR-1 बनाएँ',
    calculating: 'AI आपके डेटा का विश्लेषण कर रहा है…',
    results: 'परिणाम',
    gstLiability: 'GST देयता विवरण',
    cgst: 'CGST', sgst: 'SGST', igst: 'IGST', total: 'कुल GST देय',
    totalSales: 'कुल कर योग्य बिक्री',
    gstr1: 'GSTR-1 ड्राफ्ट सारांश',
    checklist: 'अनुपालन चेकलिस्ट',
    aiInsights: 'AI सुझाव',
    noEntries: 'GST गणना के लिए कम से कम एक बिक्री प्रविष्टि जोड़ें।',
    intra: 'अंतर्राज्यीय (समान राज्य)', inter: 'अंतरराज्यीय',
    download: 'CSV डाउनलोड करें',
    notice: 'गणित निर्धारित है। अनुपालन चेकलिस्ट केवल मार्गदर्शन के लिए Gemini AI द्वारा बनाई गई है — दाखिल करने से पहले अपने CA से पुष्टि करें।',
  },
  gu: {
    code: 'GU', label: 'ગુજરાતી',
    title: 'AI GST સહાયક',
    subtitle: 'GST જવાબદારી આપોઆપ ગણો, GSTR-1 ડ્રાફ્ટ તૈયાર કરો, અને આ મહિના માટે AI અનુપાલન ચેકલિસ્ટ મેળવો.',
    yourBiz: 'તમારો વ્યવસાય',
    bizType: 'વ્યવસાય પ્રકાર',
    bizState: 'તમારું રાજ્ય (વ્યવસાય સ્થળ)',
    salesEntries: 'માસિક વેચાણ એન્ટ્રીઓ',
    addEntry: 'એન્ટ્રી ઉમેરો',
    buyerName: 'ખરીદનારનું નામ',
    buyerState: 'ખરીદનારનું રાજ્ય',
    taxableAmt: 'કરપાત્ર રકમ (₹)',
    gstRate: 'GST દર',
    hsn: 'HSN/SAC',
    invoiceNo: 'ઇન્વોઇસ #',
    calculate: 'GST ગણો અને GSTR-1 બનાવો',
    calculating: 'AI તમારા ડેટાનું વિશ્લેષણ કરી રહ્યું છે…',
    results: 'પરિણામો',
    gstLiability: 'GST જવાબદારી વિગતો',
    cgst: 'CGST', sgst: 'SGST', igst: 'IGST', total: 'કુલ GST ચૂકવવાપાત્ર',
    totalSales: 'કુલ કરપાત્ર વેચાણ',
    gstr1: 'GSTR-1 ડ્રાફ્ટ સારાંશ',
    checklist: 'અનુપાલન ચેકલિસ્ટ',
    aiInsights: 'AI સૂચનો',
    noEntries: 'GST ગણતરી માટે ઓછામાં ઓછી એક વેચાણ એન્ટ્રી ઉમેરો.',
    intra: 'આંતર-રાજ્ય (સમાન રાજ્ય)', inter: 'આંતરરાજ્ય',
    download: 'CSV ડાઉનલોડ કરો',
    notice: 'ગણિત નિશ્ચિત છે. અનુપાલન ચેકલિસ્ટ માત્ર માર્ગદર્શન માટે Gemini AI દ્વારા બનાવવામાં આવી છે — ફાઇલિંગ પહેલાં તમારા CA સાથે ચકાસો.',
  },
};

const STATES = [
  'Gujarat', 'Maharashtra', 'Delhi', 'Karnataka', 'Tamil Nadu', 'Telangana',
  'Rajasthan', 'Madhya Pradesh', 'Uttar Pradesh', 'West Bengal', 'Punjab',
  'Haryana', 'Andhra Pradesh', 'Kerala', 'Bihar', 'Odisha', 'Jharkhand',
  'Chhattisgarh', 'Assam', 'Goa', 'Uttarakhand', 'Himachal Pradesh',
  'Jammu and Kashmir', 'Other',
];

const RATES = [0, 0.1, 3, 5, 12, 18, 28];

const BIZ_TYPES = {
  textile: { label: 'Textile', defaultRate: 5, defaultHSN: '5208' },
  diamond: { label: 'Diamond / Gems & Jewellery', defaultRate: 0.25, defaultHSN: '7102' },
  pharma: { label: 'Pharmaceutical', defaultRate: 12, defaultHSN: '3004' },
  kirana: { label: 'Kirana / FMCG', defaultRate: 5, defaultHSN: '2106' },
  manufacturing: { label: 'Manufacturing', defaultRate: 18, defaultHSN: '8479' },
  services: { label: 'Services', defaultRate: 18, defaultHSN: '9983' },
};

const fmt = (n) => '₹' + (Number(n) || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 });
const newId = () => Math.random().toString(36).slice(2, 9);

// ── deterministic GST math ────────────────────────────────────────────────────
function computeGST(entries, businessState) {
  const lines = entries.map(e => {
    const amt = Number(e.amount) || 0;
    const rate = Number(e.gstRate) || 0;
    const isIntra = (e.buyerState || '').trim().toLowerCase() === (businessState || '').trim().toLowerCase();
    const taxAmt = +(amt * rate / 100).toFixed(2);
    const cgst = isIntra ? +(taxAmt / 2).toFixed(2) : 0;
    const sgst = isIntra ? +(taxAmt / 2).toFixed(2) : 0;
    const igst = isIntra ? 0 : taxAmt;
    return { ...e, taxable: amt, rate, cgst, sgst, igst, totalTax: taxAmt, isIntra };
  });
  const totals = lines.reduce(
    (acc, l) => ({
      taxable: acc.taxable + l.taxable,
      cgst: acc.cgst + l.cgst,
      sgst: acc.sgst + l.sgst,
      igst: acc.igst + l.igst,
      totalTax: acc.totalTax + l.totalTax,
    }),
    { taxable: 0, cgst: 0, sgst: 0, igst: 0, totalTax: 0 }
  );
  return { lines, totals };
}

// ── Gemini-backed call (proxied via backend) ─────────────────────────────────
async function fetchAIInsights({ language, businessType, businessState, totals, entryCount }) {
  const res = await axios.post(`${API}/ai/gst-insights`, {
    language,
    business_type: businessType,
    business_state: businessState,
    totals: {
      taxable: totals.taxable,
      cgst: totals.cgst,
      sgst: totals.sgst,
      igst: totals.igst,
      totalTax: totals.totalTax,
    },
    entry_count: entryCount,
  });
  return res.data || { summary: '', checklist: [], tips: [] };
}

// ── COMPONENT ─────────────────────────────────────────────────────────────────
export default function GSTAssistant() {
  const [language, setLanguage] = useState('en');
  const [businessType, setBusinessType] = useState('textile');
  const [businessState, setBusinessState] = useState('Gujarat');
  const [entries, setEntries] = useState([
    { id: newId(), invoiceNo: 'INV-001', buyerName: '', buyerState: 'Gujarat', amount: '', gstRate: 5, hsn: '5208' },
  ]);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const { checkAILimits, incrementAICalls } = useAuth();

  const t = T[language];

  const addEntry = () => {
    const def = BIZ_TYPES[businessType];
    setEntries(es => [
      ...es,
      {
        id: newId(),
        invoiceNo: `INV-${String(es.length + 1).padStart(3, '0')}`,
        buyerName: '',
        buyerState: businessState,
        amount: '',
        gstRate: def.defaultRate,
        hsn: def.defaultHSN,
      },
    ]);
  };

  const removeEntry = (id) => setEntries(es => es.filter(e => e.id !== id));

  const updateEntry = (id, key, value) =>
    setEntries(es => es.map(e => (e.id === id ? { ...e, [key]: value } : e)));

  const validEntries = useMemo(
    () => entries.filter(e => Number(e.amount) > 0 && e.buyerState),
    [entries]
  );

  const handleCalculate = async () => {
    if (validEntries.length === 0) {
      toast.error(t.noEntries);
      return;
    }
    setLoading(true);
    setResult(null);
    try {
      const { lines, totals } = computeGST(validEntries, businessState);
      let ai = { summary: '', checklist: [], tips: [] };
      try {
        if (!checkAILimits()) {
          toast.error("AI usage limit reached! Please check your dashboard.");
        } else {
          ai = await fetchAIInsights({
            language, businessType, businessState, totals, entryCount: lines.length,
          });
          await incrementAICalls();
        }
      } catch (err) {
        console.error(err);
        toast.error('AI insights unavailable — showing calculations only.');
      }
      setResult({ lines, totals, ai });
      setTimeout(() => {
        document.getElementById('results-section')?.scrollIntoView({ behavior: 'smooth' });
      }, 100);
    } finally {
      setLoading(false);
    }
  };

  const downloadCSV = () => {
    if (!result) return;
    const header = ['Invoice', 'Buyer', 'Buyer State', 'HSN', 'Taxable (INR)', 'Rate %', 'CGST', 'SGST', 'IGST', 'Total Tax'];
    const rows = result.lines.map(l => [
      l.invoiceNo, l.buyerName || '-', l.buyerState, l.hsn || '-',
      l.taxable.toFixed(2), l.rate, l.cgst.toFixed(2), l.sgst.toFixed(2), l.igst.toFixed(2), l.totalTax.toFixed(2),
    ]);
    rows.push(['', '', '', 'TOTAL',
      result.totals.taxable.toFixed(2), '',
      result.totals.cgst.toFixed(2), result.totals.sgst.toFixed(2),
      result.totals.igst.toFixed(2), result.totals.totalTax.toFixed(2),
    ]);
    const csv = [header, ...rows].map(r => r.map(c => `"${c}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `GSTR1-draft-${new Date().toISOString().slice(0, 7)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-[#050505] text-white font-body">
      {/* HEADER */}
      <header className="border-b border-white/8 bg-[#0a0a0a]/80 backdrop-blur-xl sticky top-0 z-40">
        <div className="max-w-6xl mx-auto px-5 py-4 flex items-center justify-between">
          <Link to="/" data-testid="back-home" className="flex items-center gap-2 text-zinc-400 hover:text-white transition-colors text-sm">
            <ArrowLeft size={16} /> Back
          </Link>
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 bg-white rounded-md flex items-center justify-center">
              <Zap size={14} className="text-black" />
            </div>
            <span className="font-display font-bold text-sm">TaxSathi AI</span>
            <span className="mono-label text-zinc-500 ml-2 hidden sm:inline">/ GST ASSISTANT</span>
          </div>
          {/* Language Switcher */}
          <div data-testid="language-switcher" className="flex items-center gap-1 bg-white/5 border border-white/10 rounded-lg p-1">
            <Globe size={12} className="text-zinc-500 ml-1.5" />
            {Object.entries(T).map(([code, val]) => (
              <button
                key={code}
                data-testid={`lang-${code}`}
                onClick={() => setLanguage(code)}
                className={`text-xs px-2.5 py-1 rounded-md transition-all ${
                  language === code ? 'bg-white text-black font-semibold' : 'text-zinc-400 hover:text-white'
                }`}
              >
                {val.code}
              </button>
            ))}
          </div>
        </div>
      </header>

      {/* HERO */}
      <section className="px-5 pt-12 pb-8 max-w-6xl mx-auto">
        <div className="mono-label mb-3">MODULE 01 · MVP</div>
        <h1 data-testid="page-title" className="text-4xl sm:text-5xl font-bold font-display tracking-tight mb-3">
          {t.title}
        </h1>
        <p className="text-zinc-400 max-w-2xl text-base leading-relaxed">{t.subtitle}</p>
      </section>

      {/* MAIN GRID */}
      <main className="max-w-6xl mx-auto px-5 pb-24 grid lg:grid-cols-5 gap-6">
        {/* LEFT: INPUT FORM */}
        <div className="lg:col-span-3 space-y-5">
          {/* Business Info */}
          <section className="ts-card p-6">
            <div className="flex items-center gap-2 mb-4">
              <FileText size={16} className="text-[#22c55e]" />
              <h2 className="font-display font-semibold text-base">{t.yourBiz}</h2>
            </div>
            <div className="grid sm:grid-cols-2 gap-4">
              <div>
                <label className="text-zinc-500 text-xs mb-1.5 block">{t.bizType}</label>
                <select
                  data-testid="biz-type"
                  value={businessType}
                  onChange={e => setBusinessType(e.target.value)}
                  className="w-full bg-[#050505] border border-white/10 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-white/30"
                >
                  {Object.entries(BIZ_TYPES).map(([k, v]) => (
                    <option key={k} value={k}>{v.label}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="text-zinc-500 text-xs mb-1.5 block">{t.bizState}</label>
                <select
                  data-testid="biz-state"
                  value={businessState}
                  onChange={e => setBusinessState(e.target.value)}
                  className="w-full bg-[#050505] border border-white/10 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-white/30"
                >
                  {STATES.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
              </div>
            </div>
          </section>

          {/* Sales Entries */}
          <section className="ts-card p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Calculator size={16} className="text-[#60a5fa]" />
                <h2 className="font-display font-semibold text-base">{t.salesEntries}</h2>
                <span className="mono-label text-zinc-500">{entries.length}</span>
              </div>
              <button
                data-testid="add-entry-btn"
                onClick={addEntry}
                className="btn-secondary text-xs py-1.5 px-3 flex items-center gap-1.5"
              >
                <Plus size={12} /> {t.addEntry}
              </button>
            </div>

            <div className="space-y-3">
              {entries.map((e, idx) => (
                <div
                  key={e.id}
                  data-testid={`entry-row-${idx}`}
                  className="rounded-lg border border-white/8 bg-[#050505] p-4 space-y-3"
                >
                  <div className="flex items-center justify-between">
                    <span className="mono-label text-zinc-500">Entry #{idx + 1}</span>
                    {entries.length > 1 && (
                      <button
                        data-testid={`remove-entry-${idx}`}
                        onClick={() => removeEntry(e.id)}
                        className="text-zinc-500 hover:text-red-400 transition-colors"
                      >
                        <Trash2 size={14} />
                      </button>
                    )}
                  </div>
                  <div className="grid sm:grid-cols-2 gap-3">
                    <div>
                      <label className="text-zinc-500 text-[11px] mb-1 block">{t.invoiceNo}</label>
                      <input
                        data-testid={`invoice-no-${idx}`}
                        value={e.invoiceNo}
                        onChange={ev => updateEntry(e.id, 'invoiceNo', ev.target.value)}
                        className="w-full bg-[#0a0a0a] border border-white/10 rounded-md px-2.5 py-2 text-sm focus:outline-none focus:border-white/30"
                      />
                    </div>
                    <div>
                      <label className="text-zinc-500 text-[11px] mb-1 block">{t.buyerName}</label>
                      <input
                        data-testid={`buyer-name-${idx}`}
                        value={e.buyerName}
                        onChange={ev => updateEntry(e.id, 'buyerName', ev.target.value)}
                        placeholder="ABC Textiles Pvt Ltd"
                        className="w-full bg-[#0a0a0a] border border-white/10 rounded-md px-2.5 py-2 text-sm focus:outline-none focus:border-white/30"
                      />
                    </div>
                    <div>
                      <label className="text-zinc-500 text-[11px] mb-1 block">{t.buyerState}</label>
                      <select
                        data-testid={`buyer-state-${idx}`}
                        value={e.buyerState}
                        onChange={ev => updateEntry(e.id, 'buyerState', ev.target.value)}
                        className="w-full bg-[#0a0a0a] border border-white/10 rounded-md px-2.5 py-2 text-sm focus:outline-none focus:border-white/30"
                      >
                        {STATES.map(s => <option key={s} value={s}>{s}</option>)}
                      </select>
                    </div>
                    <div>
                      <label className="text-zinc-500 text-[11px] mb-1 block">{t.hsn}</label>
                      <input
                        data-testid={`hsn-${idx}`}
                        value={e.hsn}
                        onChange={ev => updateEntry(e.id, 'hsn', ev.target.value)}
                        className="w-full bg-[#0a0a0a] border border-white/10 rounded-md px-2.5 py-2 text-sm focus:outline-none focus:border-white/30"
                      />
                    </div>
                    <div>
                      <label className="text-zinc-500 text-[11px] mb-1 block">{t.taxableAmt}</label>
                      <input
                        data-testid={`amount-${idx}`}
                        type="number"
                        min="0"
                        step="0.01"
                        value={e.amount}
                        onChange={ev => updateEntry(e.id, 'amount', ev.target.value)}
                        placeholder="100000"
                        className="w-full bg-[#0a0a0a] border border-white/10 rounded-md px-2.5 py-2 text-sm focus:outline-none focus:border-white/30"
                      />
                    </div>
                    <div>
                      <label className="text-zinc-500 text-[11px] mb-1 block">{t.gstRate} (%)</label>
                      <select
                        data-testid={`rate-${idx}`}
                        value={e.gstRate}
                        onChange={ev => updateEntry(e.id, 'gstRate', Number(ev.target.value))}
                        className="w-full bg-[#0a0a0a] border border-white/10 rounded-md px-2.5 py-2 text-sm focus:outline-none focus:border-white/30"
                      >
                        {RATES.map(r => <option key={r} value={r}>{r}%</option>)}
                      </select>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <button
              data-testid="calculate-btn"
              onClick={handleCalculate}
              disabled={loading}
              className="btn-primary w-full mt-5 py-3 flex items-center justify-center gap-2 text-sm disabled:opacity-60"
            >
              {loading ? (
                <>
                  <Loader2 size={15} className="animate-spin" /> {t.calculating}
                </>
              ) : (
                <>
                  <Sparkles size={14} /> {t.calculate}
                </>
              )}
            </button>
          </section>
        </div>

        {/* RIGHT: SIDEBAR / AI INSIGHTS */}
        <aside className="lg:col-span-2 space-y-4">
          <div className="ts-card p-5">
            <div className="flex items-center gap-2 mb-3">
              <Sparkles size={14} className="text-[#a78bfa]" />
              <h3 className="font-display font-semibold text-sm">Powered by Gemini 2.5 Flash</h3>
            </div>
            <p className="text-zinc-500 text-xs leading-relaxed">
              Real-time AI compliance checklist generated for your business sector and current month.
              Math is deterministic; only insights are AI-generated.
            </p>
          </div>

          <div className="ts-card p-5 border-amber-500/20">
            <div className="flex items-start gap-2.5">
              <AlertCircle size={14} className="text-amber-400 mt-0.5 flex-shrink-0" />
              <p className="text-zinc-400 text-xs leading-relaxed">{t.notice}</p>
            </div>
          </div>

          <div className="ts-card p-5">
            <h3 className="font-display font-semibold text-sm mb-3">Quick stats</h3>
            <div className="space-y-2 text-xs">
              <div className="flex justify-between"><span className="text-zinc-500">Entries added</span><span className="text-white font-mono">{entries.length}</span></div>
              <div className="flex justify-between"><span className="text-zinc-500">Valid entries</span><span className="text-white font-mono">{validEntries.length}</span></div>
              <div className="flex justify-between"><span className="text-zinc-500">Period</span><span className="text-white font-mono">{new Date().toLocaleString('en-IN', { month: 'short', year: 'numeric' })}</span></div>
            </div>
          </div>
        </aside>

        {/* RESULTS – full width below */}
        {result && (
          <section id="results-section" data-testid="results-section" className="lg:col-span-5 mt-6 space-y-5">
            <div className="flex items-center justify-between">
              <h2 className="font-display font-bold text-2xl">{t.results}</h2>
              <button
                data-testid="download-csv-btn"
                onClick={downloadCSV}
                className="btn-secondary text-xs py-2 px-3 flex items-center gap-1.5"
              >
                <Download size={12} /> {t.download}
              </button>
            </div>

            {/* GST Liability Cards */}
            <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
              {[
                { k: 'totalSales', val: result.totals.taxable, color: '#60a5fa', testid: 'kpi-taxable' },
                { k: 'cgst', val: result.totals.cgst, color: '#22c55e', testid: 'kpi-cgst' },
                { k: 'sgst', val: result.totals.sgst, color: '#a78bfa', testid: 'kpi-sgst' },
                { k: 'igst', val: result.totals.igst, color: '#f59e0b', testid: 'kpi-igst' },
                { k: 'total', val: result.totals.totalTax, color: '#ffffff', testid: 'kpi-total', highlight: true },
              ].map(card => (
                <div
                  key={card.k}
                  data-testid={card.testid}
                  className={`ts-card p-4 ${card.highlight ? 'bg-white text-black border-white' : ''}`}
                >
                  <div className={`mono-label mb-2 ${card.highlight ? 'text-black/50' : ''}`}>{t[card.k]}</div>
                  <div
                    className="font-display font-bold text-xl"
                    style={card.highlight ? { color: '#000' } : { color: card.color }}
                  >
                    {fmt(card.val)}
                  </div>
                </div>
              ))}
            </div>

            {/* GSTR-1 Draft Table */}
            <div className="ts-card p-6">
              <div className="flex items-center gap-2 mb-4">
                <FileText size={16} className="text-[#22c55e]" />
                <h3 className="font-display font-semibold">{t.gstr1}</h3>
              </div>
              <div className="overflow-x-auto">
                <table data-testid="gstr1-table" className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-white/10 text-zinc-500">
                      {[t.invoiceNo, t.buyerName, t.buyerState, t.hsn, t.taxableAmt, t.gstRate, t.cgst, t.sgst, t.igst].map(h => (
                        <th key={h} className="text-left py-2 px-2 font-normal">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {result.lines.map((l, i) => (
                      <tr key={l.id} data-testid={`gstr1-row-${i}`} className="border-b border-white/5">
                        <td className="py-2 px-2 font-mono">{l.invoiceNo}</td>
                        <td className="py-2 px-2">{l.buyerName || '—'}</td>
                        <td className="py-2 px-2">
                          <span className="text-zinc-400">{l.buyerState}</span>
                          <span className={`ml-1.5 mono-label text-[9px] ${l.isIntra ? 'text-[#22c55e]' : 'text-[#f59e0b]'}`}>
                            {l.isIntra ? t.intra : t.inter}
                          </span>
                        </td>
                        <td className="py-2 px-2 font-mono">{l.hsn || '—'}</td>
                        <td className="py-2 px-2 font-mono">{fmt(l.taxable)}</td>
                        <td className="py-2 px-2 font-mono">{l.rate}%</td>
                        <td className="py-2 px-2 font-mono text-[#22c55e]">{fmt(l.cgst)}</td>
                        <td className="py-2 px-2 font-mono text-[#a78bfa]">{fmt(l.sgst)}</td>
                        <td className="py-2 px-2 font-mono text-[#f59e0b]">{fmt(l.igst)}</td>
                      </tr>
                    ))}
                    <tr className="font-semibold">
                      <td colSpan="4" className="py-3 px-2 text-right text-zinc-400">TOTAL</td>
                      <td className="py-3 px-2 font-mono text-white">{fmt(result.totals.taxable)}</td>
                      <td></td>
                      <td className="py-3 px-2 font-mono text-[#22c55e]">{fmt(result.totals.cgst)}</td>
                      <td className="py-3 px-2 font-mono text-[#a78bfa]">{fmt(result.totals.sgst)}</td>
                      <td className="py-3 px-2 font-mono text-[#f59e0b]">{fmt(result.totals.igst)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            {/* AI Summary */}
            {result.ai?.summary && (
              <div className="ts-card p-6">
                <div className="flex items-center gap-2 mb-3">
                  <Sparkles size={16} className="text-[#a78bfa]" />
                  <h3 className="font-display font-semibold">{t.aiInsights}</h3>
                </div>
                <p data-testid="ai-summary" className="text-zinc-300 text-sm leading-relaxed">{result.ai.summary}</p>
                {result.ai.tips?.length > 0 && (
                  <ul className="mt-4 space-y-2">
                    {result.ai.tips.map((tip, i) => (
                      <li key={i} data-testid={`ai-tip-${i}`} className="flex items-start gap-2 text-sm text-zinc-400">
                        <span className="text-[#a78bfa] mt-0.5">▹</span>
                        <span>{tip}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            )}

            {/* Compliance Checklist */}
            {result.ai?.checklist?.length > 0 && (
              <div className="ts-card p-6">
                <div className="flex items-center gap-2 mb-4">
                  <CheckCircle2 size={16} className="text-[#22c55e]" />
                  <h3 className="font-display font-semibold">{t.checklist}</h3>
                </div>
                <ul data-testid="checklist" className="space-y-2.5">
                  {result.ai.checklist.map((item, i) => (
                    <li key={i} data-testid={`checklist-item-${i}`} className="flex items-start gap-3 text-sm">
                      <CheckCircle2 size={14} className="text-[#22c55e] mt-0.5 flex-shrink-0" />
                      <span className="text-zinc-300 leading-relaxed">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </section>
        )}
      </main>
    </div>
  );
}
